[bind_addr]
bind_addr = ":8080"
log_level = "debug"

[database.master]
host = "db"
port = "5432"
user = "postgres"
password = "password"
dbname = "images_db"
ssl_mode = "disable"

[[database.slaves]]
# Оставь пустым или добавь при масштабировании
# host = "replica1"
# port = "5432"
# user = "postgres"
# pass = ""
# name = "images_db_replica"
# ssl_mode = "disable"

database.max_open_conns = 10
database.max_idle_conns = 5
database.conn_max_lifetime = "30m"

[storage]
endpoint = "minio:9000"
access_key = "minioadmin"
secret_key = "minioadmin"
bucket_name = "image-bucket"
use_ssl = false

[kafka]
group_id = "image-workers"
topic = "image.uploaded"
brokers = ["kafka:9092"]
